"""The graph-node record table and the comparison specification it is linked under.

A node carries more than the normalized name the builder keys it on: every surface form it was
seen under, the ontology type it was assigned, the documents its mentions cite, and the text of
those mentions. Each becomes an agreement ladder, so a proposed merge arrives as a match
probability with the agreements behind it instead of a string equality test.

The blocking keys reuse `graph.linking.morph_key` -- the same dependency-free Ukrainian stem the
question linker already keys on -- so a candidate pair is generated by exactly the morphology the
retrieval path assumes, and no lemmatizer enters the build.
"""

from collections.abc import Sequence

from llb.core.contracts.common import JsonObject
from llb.graph.linking import morph_key, tokenize
from llb.graph.model import GraphNode, KnowledgeGraph
from llb.graph.resolution.constants import (
    DOC_ID_SIZES,
    DOC_IDS_COLUMN,
    ENTITY_TYPE_COLUMN,
    HEAD_KEY_COLUMN,
    MAX_NODE_TEXT_CHARS,
    MENTION_COSINE_THRESHOLDS,
    MENTION_VECTOR_COLUMN,
    N_MENTIONS_COLUMN,
    NAME_COLUMN,
    NAME_SIMILARITY_THRESHOLDS,
    NODE_ID_COLUMN,
    RETAIN_COLUMNS,
    SURFACE_FORM_SIZES,
    SURFACE_FORMS_COLUMN,
    TAIL_KEY_COLUMN,
)
from llb.linkage.constants import (
    KIND_ARRAY_INTERSECT,
    KIND_COSINE,
    KIND_EXACT,
    KIND_JARO_WINKLER,
)
from llb.linkage.spec import BlockingRule, ComparisonSpec, LinkageSpec

Vector = list[float]


def record_id(node_id: int) -> str:
    """A zero-padded record identifier, so the table sorts the way the node list is numbered."""
    return f"node-{node_id:06d}"


def node_id_of(record_id_value: str) -> int:
    """The node id a record identifier was built from."""
    return int(str(record_id_value).rsplit("-", 1)[-1])


def surface_forms(node: GraphNode) -> list[str]:
    """Every form the node was seen under -- its own name included -- normalized and deduplicated.

    The name belongs in the array because that is exactly how an entity fragments: the builder
    merges an alias onto a node whose NAME matches, so the second node's name is often the first
    node's alias. Comparing aliases without names would miss the case the pass exists for.
    """
    forms = {" ".join(str(node.name).split()).casefold()}
    forms.update(" ".join(str(alias).split()).casefold() for alias in node.aliases)
    return sorted(form for form in forms if form)


def doc_ids(node: GraphNode) -> list[str]:
    """The documents the node's mentions cite, deduplicated and ordered."""
    return sorted({mention["doc_id"] for mention in node.mentions})


def blocking_keys(node: GraphNode) -> tuple[str, str]:
    """The (head, tail) morphological stems the node's name blocks on.

    A Ukrainian full name puts the surname LAST, so the tail key is what blocks a surname-only
    node against its own full name and against every inflected form of either. Multiword
    institution names agree on their first word instead, which is what the head key blocks.
    An unnamed node keys on the empty string and is therefore blocked only by its entity type.
    """
    tokens = [token for token in str(node.name).split() if tokenize(token)]
    if not tokens:
        return "", ""
    return morph_key(tokens[0].casefold()), morph_key(tokens[-1].casefold())


def node_text(node: GraphNode) -> str:
    """What the node's mention embedding is taken over: its surface forms, then its mentions."""
    parts = [str(node.name), *(str(alias) for alias in node.aliases)]
    parts.extend(str(mention["text"]) for mention in node.mentions)
    text = " ".join(part.strip() for part in parts if part.strip())
    return text[:MAX_NODE_TEXT_CHARS]


def build_records(
    graph: KnowledgeGraph, mention_vectors: Sequence[Vector] | None = None
) -> list[JsonObject]:
    """One record per graph node, in node order, with the mention vectors already embedded."""
    if mention_vectors is not None and len(mention_vectors) != len(graph.nodes):
        raise ValueError("mention vectors must align one-to-one with the graph's nodes")
    records: list[JsonObject] = []
    for index, node in enumerate(graph.nodes):
        head_key, tail_key = blocking_keys(node)
        record: JsonObject = {
            "unique_id": record_id(node.node_id),
            NODE_ID_COLUMN: str(node.node_id),
            NAME_COLUMN: node.name,
            SURFACE_FORMS_COLUMN: surface_forms(node),
            ENTITY_TYPE_COLUMN: node.type,
            DOC_IDS_COLUMN: doc_ids(node),
            HEAD_KEY_COLUMN: head_key,
            TAIL_KEY_COLUMN: tail_key,
            N_MENTIONS_COLUMN: str(len(node.mentions)),
        }
        if mention_vectors is not None:
            record[MENTION_VECTOR_COLUMN] = list(mention_vectors[index])
        records.append(record)
    return records


def build_node_spec(mention_dimension: int, match_threshold: float) -> LinkageSpec:
    """The graph-node comparison specification, at the embedding width the run produced.

    `mention_dimension` of 0 drops the cosine comparison entirely: a run with no embedder still
    has four agreement ladders, which is what the seam's two-comparison floor asks for, and the
    absent signal is visible in the specification rather than silently zero-filled.
    """
    comparisons = [
        ComparisonSpec(
            column=NAME_COLUMN,
            kind=KIND_JARO_WINKLER,
            thresholds=NAME_SIMILARITY_THRESHOLDS,
        ),
        ComparisonSpec(
            column=SURFACE_FORMS_COLUMN,
            kind=KIND_ARRAY_INTERSECT,
            thresholds=SURFACE_FORM_SIZES,
        ),
        ComparisonSpec(column=ENTITY_TYPE_COLUMN, kind=KIND_EXACT),
        ComparisonSpec(
            column=DOC_IDS_COLUMN,
            kind=KIND_ARRAY_INTERSECT,
            thresholds=DOC_ID_SIZES,
        ),
    ]
    if mention_dimension > 0:
        comparisons.append(
            ComparisonSpec(
                column=MENTION_VECTOR_COLUMN,
                kind=KIND_COSINE,
                thresholds=MENTION_COSINE_THRESHOLDS,
                dimension=mention_dimension,
            )
        )
    spec = LinkageSpec(
        comparisons=tuple(comparisons),
        blocking_rules=(
            BlockingRule((TAIL_KEY_COLUMN,)),
            BlockingRule((HEAD_KEY_COLUMN,)),
            BlockingRule((ENTITY_TYPE_COLUMN,)),
        ),
        # The entity-type pass is what trains the NAME, and it has to be: a stem key is very
        # nearly a function of the name, so a pass blocked on one sees no name variation to learn
        # from and lands m below u on the very level a same-entity pair agrees at. Blocking on the
        # type instead leaves the name free to vary, and the tail-stem pass then trains the type
        # the first pass held fixed. Two passes, and each covers what the other cannot.
        training_rules=(
            BlockingRule((ENTITY_TYPE_COLUMN,)),
            BlockingRule((TAIL_KEY_COLUMN,)),
        ),
        retain_columns=RETAIN_COLUMNS,
        match_threshold=match_threshold,
    )
    spec.validate()
    return spec
