"""The function-word table the answer-side span metric matches against (data only).

Two things go wrong without it: a preposition the span and the reference happen to share becomes a
"fact" an unrelated span can be judged on, and a correct but TERSE answer falls under the cut
because the requirement counts the wording it dropped. Both surface forms and lemmas are listed and
`llb.scoring.answer_spans` drops a token matching EITHER, so an unlisted inflection is caught by its
lemma while a first-parse artefact of the analyzer (`bula -> bulyi`) is caught by its surface form.

The table is scoring-owned on purpose. Other modules keep their own (topic grouping in
`llb.board.miss_analysis`, salient terms in `llb.prompt_system.corpus`); those are heuristics tuned
to their own job, and a published metric may not move because one of them was retuned.
"""

FUNCTION_WORDS = frozenset(
    {
        # conjunctions, particles, interrogatives
        "а",
        "але",
        "б",
        "би",
        "бо",
        "ж",
        "або",
        "чи",
        "що",
        "щоб",
        "як",
        "не",
        "ні",
        "так",
        "теж",
        "також",
        "лише",
        "тільки",
        "вже",
        "ще",
        "навіть",
        "і",
        "й",
        "та",
        # prepositions
        "в",
        "у",
        "на",
        "з",
        "із",
        "зі",
        "до",
        "від",
        "для",
        "про",
        "при",
        "по",
        "за",
        "під",
        "над",
        "між",
        "через",
        "без",
        "після",
        "перед",
        "біля",
        "щодо",
        # pronouns and determiners, surface forms plus their lemmas
        "який",
        "яка",
        "яке",
        "які",
        "якого",
        "якої",
        "яким",
        "це",
        "цей",
        "ця",
        "ці",
        "цього",
        "цієї",
        "цьому",
        "той",
        "те",
        "ті",
        "того",
        "тієї",
        "він",
        "вона",
        "воно",
        "вони",
        "його",
        "її",
        "їх",
        "йому",
        "їй",
        "їм",
        "ми",
        "ви",
        "я",
        "ти",
        "мене",
        "тебе",
        "нас",
        "вас",
        "свій",
        "своя",
        "своє",
        "свої",
        "своїх",
        "мій",
        "твій",
        "наш",
        "ваш",
        "весь",
        "вся",
        "все",
        "всі",
        "усі",
        "усе",
        "ввесь",
        # the copula, whose forms carry no fact of their own
        "є",
        "був",
        "була",
        "було",
        "були",
        "буде",
        "будуть",
        "бути",
        # English, for a mixed-script corpus
        "a",
        "an",
        "and",
        "are",
        "be",
        "by",
        "for",
        "in",
        "is",
        "it",
        "its",
        "of",
        "on",
        "or",
        "that",
        "the",
        "this",
        "to",
        "was",
        "were",
        "with",
    }
)

__all__ = ["FUNCTION_WORDS"]
